### ISSUE TITLE
How to select video codec for video call

### ISSUE THREAD

**Issue by mehturt** [RestComm/restcomm-android-sdk#288]
How to select video codec for video call? I see that in RCConnection.java it always uses VP8 and HW acceleration enabled, is there a way to change this?
I think my peer only support H264.

**Comment by atsakiridis** [comment]
Hm, not sure about that. I would assume that there would be some sort of constraint when initializing media with webrtc, so that generated SDP offer uses the codec you want. I would suggest that you post a question to stackoverflow for such questions to gain more visibility and also add the 'restcomm' tag

**Comment by mehturt** [comment]
I was asking because in the Android SDK in initializeWebrtc() I see "VP8" hardcoded, not sure if it means only "VP8" is supported?

**Comment by atsakiridis** [comment]
Hm, good question. Not sure, why don't you check what happens in https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.client.sdk/src/main/java/org/mobicents/restcomm/android/client/sdk/PeerConnectionClient.java, seems to be setting the codec there somehow

**Comment by mehturt** [comment]
I was trying to debug this but did not get to the bottom of how this works.
