### ISSUE TITLE
Provide list of registration domain usernames in Android Olympus

### ISSUE THREAD

**Issue by leftyb** [RestComm/restcomm-android-sdk#388]
In the Olympus Settings Screen having the option to have a list of domains (associated with a username & password) instead of only one will improve the UX. This way user can change between domain servers, with just selecting out of a list which users without the need to change every time the  configuration.

**Comment by deruelle** [comment]
I started to notice that as well while testing, I guess though this won't be the most common usage so I UI/UX wise it may not be needed to make that prominent

**Comment by ionicc** [comment]
So the user adds more domains in the settings itself to switch or the app just captures all the domains that are being login in Olympus?

**Comment by atsakiridis** [comment]
@ionicc bit of both I guess ;). Imagine that when we test we tend to use more than one domains, each of which goes together with username & password. Would be great if the user wants to use a previously used domain, they can just select it and not have to write it all down. Also they don't need to write username and password again they should be saved per domain. So each time a user selects a *new* domain, username & pass they should be saved. Then, the user should be able to choose based on previously saved domain & credentials.

Please feel free to adjust UI/UX in the Settings activity/screen as you feel would make best sense to accommodate new functionality. In fact, I would suggest that you start by thinking about UI/UX and come up with a proposal (using wireframes, or whatever works best for you to present it) on how you think this would make more sense. Then we can discuss on it and once we agree on the final design you can start with actual implementation. Also, most importantly, bear in mind that right now we 're using a specialized fragment, SettingsFragment (that extends PreferenceFragment and works with Preferences storage out of the box), not a generic fragment, so you need to take that into account as well and see if you can accommodate the needed functionality but at the same time combine with PreferenceFragment so that we keep the benefits of the latter. What do you think?

**Comment by ionicc** [comment]
Instead of providing a list we should just provide a logout button in the MainActivity. The Username, Passwords and the domains will be stored in SharedPreferences which will not be quite safe as any rooted phone will be able to access them.

**Comment by ionicc** [comment]
If we had a token system in place for login then we could've used the tokens for storing the recent contacts but as that is not in place, I think it would be best to give the user the provision to logout and login again

**Comment by atsakiridis** [comment]
@ionicc lets not get too crazy about security at this point. Remember that Olympus is just a sample/demo App on how a customer/community can utilize our SDK. Interested customers will implement their own Apps and will be responsible in doing it in a secure manner.

On log out button, the problem is that you don't solve the problem which is ease of switching between accounts and remembering previous domains & credentials.

Finally, the way it works right now you can switch domain and user, but you have to edit all the Settings by hand and then hit back button. At that point the SDK will try to re-register with Restcomm using new credentials. But all that is tedious and hence this issue on making it easier

**Comment by atsakiridis** [comment]
Per our current focus this is no longer applicable
