### ISSUE TITLE
Access to constructor not allowed

### ISSUE THREAD

**Issue by ArtemNeFRiT** [RestComm/restcomm-android-sdk#453]
Hello! 
I have the folowing code in my Activity:
`@Override
protected void onStart() {super.onStart();
        bindService(new Intent(this, RCDevice.class), this, Context.BIND_AUTO_CREATE);
    }`
that throws IllegalAccessException: access to constructor not allowed RCDevice.
The same exception in HelloWorld sample app. How to fix this?

**Comment by atsakiridis** [comment]
Hi @ArtemNeFRiT, 

Can you paste full logcat of the scenario when using HelloWorld sample App? If you have cloned the repository, which commit are you at? If using a GitHub release, which one is it?

**Comment by ArtemNeFRiT** [comment]
[logcat.txt](https://github.com/RestComm/restcomm-android-sdk/files/585782/logcat.txt)
I am running this [this](https://github.com/RestComm/restcomm-android-sdk/releases/tag/v1.0.0-BETA4) Hello World sample.
Without any code modification, I just trying to launch sample.
Working in Android Studio 2.2.2 and Samsung Galaxy S4 with Android 5.0.1

**Comment by atsakiridis** [comment]
@ArtemNeFRiT thanks for the info. It's really weird that you get this issue, because for me the code for 1.0.0-BETA4 release for Hello World sample is working fine -just verified. In any case, I did change the RCDevice constructor from package-private to public, to see if it fixes your issue. 

So can you edit RCDevice.java file and make RCDevice constructor public as shown in:

https://github.com/RestComm/restcomm-android-sdk/commit/be3456d6f84d2d7d9df347e5ee17e33a0f72290d#diff-0179ea7f556a7543b2d8e0d7e2fd6b31

And rebuild and tell me the results?

Best regards,
Antonis

**Comment by ArtemNeFRiT** [comment]
Yes, now problem is gone, thanks @atsakiridis.

**Comment by atsakiridis** [comment]
Awesome 👍
