### ISSUE TITLE
Route in SIP REGISTER request

### ISSUE THREAD

**Issue by WolandPL** [RestComm/restcomm-android-sdk#595]
SIGNALING_DOMAIN is required for non-registrarless usage of SIP, but it seems that if it's set it forces "Route" header in SIP REGISTER request. If I'm not mistaken "Route" makes sense only if there's a SIP proxy in front of "real" SIP server and if not it seems to confuse the server - I'm not receiving any responses to my REGISTER request and the server team says it's because of unneeded "Route" header in the request.

Correct my if I'm wrong - I'm new to SIP, but I've seen REGISTER requests from sources other than Restcomm Android SDK that didn't have "Route" header but it seems impossible to send such request using our SDK.

**Comment by atsakiridis** [comment]
@WolandPL we added the Route header a while back to workaround an issue we had, but indeed its not required and actually we already have an [issue](https://github.com/RestComm/restcomm-android-sdk/issues/421) about this, which we haven't had time to look at :( because it never caused any issues in our env.

Would you be interested to bite the bullet and contribute this? We 'll be here to help you of course if you need anything.

Best regards

**Comment by WolandPL** [comment]
@atsakiridis Thanks for your answer. Well, actually this seems to be a false alarm. Route header should not cause problems for the server. My requests containing this header work fine with your server (on cloud.restcomm.com) but not with my customer's server, so the conclusion is that the problem is on server side.

**Comment by atsakiridis** [comment]
Ok cool, closing issue
