### ISSUE TITLE
Unable to register restcomm olympus app on 3G

### ISSUE THREAD

**Issue by tahirjilani** [RestComm/restcomm-android-sdk#633]
On Wi-Fi it works fine but on 3G cellular network it gives error: 
Device couldn't connect to server

Attached are the logs.
[restcomm-3g.txt](https://github.com/RestComm/restcomm-android-sdk/files/1111611/restcomm-3g.txt)

A quick help would be highly appreciated.

**Comment by atsakiridis** [comment]
@tahirjilani the problem seems to be here:

```
06-29 14:08:29.344 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni7][9]
06-29 14:08:29.345 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni7][9] isUp: false
06-29 14:08:29.346 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni6][8]
06-29 14:08:29.347 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni6][8] isUp: false
06-29 14:08:29.347 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni5][7]
06-29 14:08:29.348 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni5][7] isUp: false
06-29 14:08:29.349 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni1][3]
06-29 14:08:29.350 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni1][3] isUp: false
06-29 14:08:29.351 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni0][2][/10.69.246.142]
06-29 14:08:29.352 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni0][2][/10.69.246.142] isUp: true
06-29 14:08:29.352 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni4][6]
06-29 14:08:29.353 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni4][6] isUp: false
06-29 14:08:29.354 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni3][5]
06-29 14:08:29.355 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni3][5] isUp: false
06-29 14:08:29.356 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ccmni2][4]
06-29 14:08:29.357 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ccmni2][4] isUp: false
06-29 14:08:29.357 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [wlan0][35]
06-29 14:08:29.358 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [wlan0][35] isUp: true
06-29 14:08:29.359 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [tunl0][12]
06-29 14:08:29.360 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [tunl0][12] isUp: false
06-29 14:08:29.361 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [lo][1][/::1%1%1][/127.0.0.1]
06-29 14:08:29.362 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [lo][1][/::1%1%1][/127.0.0.1] isUp: true
06-29 14:08:29.363 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [sit0][13]
06-29 14:08:29.364 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [sit0][13] isUp: false
06-29 14:08:29.364 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [p2p0][36]
06-29 14:08:29.365 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [p2p0][36] isUp: false
06-29 14:08:29.366 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ifb1][11]
06-29 14:08:29.367 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ifb1][11] isUp: false
06-29 14:08:29.368 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ifb0][10]
06-29 14:08:29.368 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ifb0][10] isUp: false
06-29 14:08:29.369 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Current interface: [ip6tnl0][14]
06-29 14:08:29.371 14889-14995/org.restcomm.android.olympus I/JainSipClient: interface2Address(): Interface not matching or down: [ip6tnl0][14] isUp: false
06-29 14:08:29.371 14889-14995/org.restcomm.android.olympus V/JainSipClient: interface2Address(): stringAddress: , for currently active network: rmnet, interfaces: [[ccmni7][9], [ccmni6][8], [ccmni5][7], [ccmni1][3], [ccmni0][2][/10.69.246.142], [ccmni4][6], [ccmni3][5], [ccmni2][4], [wlan0][35], [tunl0][12], [lo][1][/::1%1%1][/127.0.0.1], [sit0][13], [p2p0][36], [ifb1][11], [ifb0][10], [ip6tnl0][14]]
06-29 14:08:29.372 14889-14995/org.restcomm.android.olympus E/JainSipClient: Couldn't retrieve IP address for currently active network
06-29 14:08:29.373 14889-14995/org.restcomm.android.olympus V/JainSipClient: getIPAddress(): 
06-29 14:08:29.373 14889-14995/org.restcomm.android.olympus I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
```

And more specifically `Couldn't retrieve IP address for currently active network`. If you grep this last message in SDK code you will see that for real devices the cellular data interface is expected to be called `rmnet`, and in your case I don't think that's the case. Are you sure you are actually using cellular data and not any weird interface (maybe VPN)? If so what is the interface name and IP address? ccmni/10.69.246.142?

Best regards,
Antonis

**Comment by tahirjilani** [comment]
@atsakiridis 
No I am not using VPN or wired interface, I am using 3G service from mobilink gsm provider on my fathers farm house.
i just debugged the code and found out the following interfaces entries:

networkInterfacePrefix: rmnet

interfaces = {ArrayList@6261}  size = 11
 0 = {NetworkInterface@6262} "[lo][1][/::1%1%1][/127.0.0.1]"
 1 = {NetworkInterface@6275} "[sit0][5]"
 2 = {NetworkInterface@6280} "[ifb1][3]"
 3 = {NetworkInterface@6281} "[ifb0][2]"
 4 = {NetworkInterface@6282} "[p2p0][11]"
 5 = {NetworkInterface@6283} "[wlan0][10]"
 6 = {NetworkInterface@6284} "[tunl0][4]"
 7 = {NetworkInterface@6285} "[ccmni2][9]"
 8 = {NetworkInterface@6286} "[ccmni1][8]"
 9 = {NetworkInterface@6287} "[ccmni0][7][/10.92.231.15]"
 10 = {NetworkInterface@6288} "[ip6tnl0][6]"

and getIPAddress method returns "" string which is causing the issue. However, I made a small change in the code like:
        else {
            // Real device
            stringAddress = interface2Address(useIPv4, "rmnet|ccmni");
         }
and getIPAddress returns me 10.92.231.15 and user gets registered.

Attached are the logs.
[logs2.txt](https://github.com/RestComm/restcomm-android-sdk/files/1113107/logs2.txt)

do you think its a viable solution by altering networkInterfacePrefix from "rmnet" to "rmnet|ccmni"?

**Comment by atsakiridis** [comment]
@tahirjilani I'd like to avoid putting there interface names that are not 100% standard. Back when we wrote this code the only 'standard' we found was 'rmnet' and this has worked fine so far. Another issue on adding more than 1 for cellular data is having to chose between multiple in edge scenarios and getting the wrong one.

Thinking more about it, do you think you can do some investigation, see if there's a way to amend code there to avoid depending on cellular data interface name? Maybe somehow figure out its type and if it is cellular-data type then use it. I believe we didn't find a way back then, but maybe we missed something

**Comment by tahirjilani** [comment]
@atsakiridis i've created attached class. that returns me correct ip address of 3G connectivity. Now I am 100% not specifying interface names and we are using android native functions.
Following are the network interfaces on my phone:

interfaces = {ArrayList@6217}  size = 16
 0 = {NetworkInterface@6220} "[ccmni7][9]"
 1 = {NetworkInterface@6221} "[ccmni6][8]"
 2 = {NetworkInterface@6222} "[ccmni5][7]"
 3 = {NetworkInterface@6223} "[ccmni1][3]"
 4 = {NetworkInterface@6224} "[ccmni0][2][/10.232.101.81]"
 5 = {NetworkInterface@6225} "[ccmni4][6]"
 6 = {NetworkInterface@6226} "[ccmni3][5]"
 7 = {NetworkInterface@6227} "[ccmni2][4]"
 8 = {NetworkInterface@6228} "[wlan0][17]"
 9 = {NetworkInterface@6229} "[tunl0][12]"
 10 = {NetworkInterface@6230} "[lo][1][/::1%1%1][/127.0.0.1]"
 11 = {NetworkInterface@6231} "[sit0][13]"
 12 = {NetworkInterface@6232} "[p2p0][18]"
 13 = {NetworkInterface@6233} "[ifb1][11]"
 14 = {NetworkInterface@6234} "[ifb0][10]"
 15 = {NetworkInterface@6235} "[ip6tnl0][14]"

Connectivity.getDeviceIpv4Address(androidContext) returns me 10.232.101.81
which is currently active network. and using this IP i am able to REGISTER successfully.
I/System.out: close [socket][/10.232.101.81:44900]

(Note: taken help from Stackoverflow to write this class)
[Connectivity.java.txt](https://github.com/RestComm/restcomm-android-sdk/files/1117659/Connectivity.java.txt)

**Comment by atsakiridis** [comment]
Thanks for your effort @tahirjilani! A couple of notes from my side:
- We already have a similar class to handle network connectivity changes, please check [JainSipNotificationManager.java](https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipNotificationManager.java). Notice that we need to support ethernet as well apart from Wifi & Cellular, which is very important for stationery Android devices
- Also similar handling as getLocalisIpv4Address, is located [here](https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipClient.java#L983) and [here](https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipClient.java#L935).
- Best approach would be if Android provided an API to denote type of interface so that you can tell if a specific interface is cellular or not, but I think thats not possible -did you investigate that just in case?
- The issue with the current SDK code is that we wanted to take a safe approach and enable any cellular data interface explicitly when we make sure there's a need for it (so far rmnet* has covered us). Since there are a lot of weird interfaces in Android we wanted to make sure we don't select any interface by mistake simply because it is up and has an IP associated with it. So for now I would prefer to go for white-listing ccmni* as you suggested originally. If we see in the future that indeed we get a lot of such cases we can be more aggressive and leave the white-listing logic out.

That said would you like to prepare a Pull Request with that? Is there any functionality from your suggested class that we are currently missing in the SDK and which you think makes sense to introduce? If so please let me know so that we can discuss.

Finally, can you share what device you use that has this ccmni interface, so that I can have a look?

**Comment by tahirjilani** [comment]
@atsakiridis 
Following are device info that has ccmni interface. And above logs were from same device.

> Hardware information: 
> OS Version: 23
> Board: unknown
> Boot Loader: unknown
> Brand: Lenovo
> CPU ABI: armeabi-v7a
> CPU_ABI2: armeabi
> Device: A7010a48
> Display: A7010a48_S232_161227_ROW
> Finger Print: Lenovo/k5fpr/A7010a48:6.0/MRA58K/RA7010a48_S232_161227_ROW.12271429:user/release-keys
> Hardware: mt6735
> Host: njbs15
> ID: MRA58K
> Manufecturer: LENOVO
> Model: Lenovo A7010a48
> Product: k5fpr
> Radio: unknown
> Tag: release-keys
> Type: user

By the way does Restcomm support ipv6? I see getIPAddress(boolean useIPv4=true) being used in the code and ipv6 are ignored. I've seen a strange behavior on a device from USA I have attached the logs and a screenshot. That device seems to have ipv6 configurations from LTE provider.
Can you please have a look at it:

![screenshot_2017-07-05-01-51-11](https://user-images.githubusercontent.com/10370852/27872020-e140d8ae-61c0-11e7-8bff-df91ade7394e.png)
[shop-logs (5).txt](https://github.com/RestComm/restcomm-android-sdk/files/1125206/shop-logs.5.txt)

**Comment by tahirjilani** [comment]
@atsakiridis You can see the ipv6 being listed in the logs attached in my previous comment:
interface2Address(): stringAddress: , for currently active network: rmnet, interfaces: [[rmnet1][5][/2607:fb90:4627:ac3c:0:36:95c6:da01%5%5][/fe80::68d0:676b:f494:365c%rmnet1%5], [rmnet0][4][/2607:fb90:465a:8334:0:36:95c6:d401%4%4][/fe80::6ad3:eae8:d035:7f37%rmnet0%4], [rmnet7][11], [rmnet5][9], [rmnet6][10], [rmnet4][8], [rmnet2][6], [rmnet3][7], [dummy0][2], [v4-rmnet0][44][/192.0.0.4], [epdg3][15], [epdg2][14], [epdg0][12], [epdg1][13], [epdg4][16], [wlan0][17], [p2p0][18], [sit0][3], [lo][1][/::1%1%1][/127.0.0.1]]
Jul 5, 2017 3:05:01 AM:  JainSipClient:   Couldn't retrieve IP address for currently active network

**Comment by atsakiridis** [comment]
@tahirjilani the SDK hasn't been tested with IPV6 yet which is why we are always requesting IPV4 in the code. It's possible that it might work since webrtc should support it from media side and JAIN SIP should support it from signaling side. But thats just the stacks running locally; you then need to check what other network elements you have in your scenario and make sure all interoperate. Still you need to test to verify ;). Would you be interested to? We can help along the way as much as we can. 

First step would be in calling interface2Address() with useIPv4 false and see what happens when the signaling stack tries to bootstrap with an IPv6 address.

**Comment by atsakiridis** [comment]
@tahirjilani closing this as I haven't received reply in long time. Please feel free to reopen if this still happens so that we can discuss

**Comment by gsaslis** [comment]
@suyashbhatt this was fixed by #845 after all, right?

**Comment by suyashbhatt** [comment]
@gsaslis Yes it is fixed

**Comment by suyashbhatt** [comment]
It was not working because rmnet0 is providing ipv6 and regular expression was not picking up v4-rmnet0 which provides ipv4.

**Comment by gsaslis** [comment]
awesome, thanks! 👍
