### ISSUE TITLE
JainSipMessageBuilder removes valid '-' characters from Sip address host part

### ISSUE THREAD

**Issue by abdulazizali77** [RestComm/restcomm-android-sdk#694]
@atsakiridis 
Antonis, from what i understand the dashes are only to be removed from the number. But currently this is being removed from Sip host parts too.
https://github.com/RestComm/restcomm-android-sdk/blob/3d6798c858e6fedad661150ff129517eebee481f/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipMessageBuilder.java#L127

Taking this example: https://en.wikipedia.org/wiki/SIP_URI_scheme
`sip:1-999-123-4567@voip-provider.example.net` becomes
`sip:19991234567@voipprovider.example.net` which is wrong

**Comment by atsakiridis** [comment]
Adding comment from PR here too for better tracking:

@abdulazizali77 thanks a lot for the contribution! However, it so happens that I'm working at the exact same [issue](https://telestax.zendesk.com/agent/tickets/34666) since yday (what are the odds), and this needs more thought. Turns out we need to support dashes even in the user part (for example client 'test-user' which is valid) and generally I prefer, if needed, to address such handling earlier, like [here](https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipMessageBuilder.java#L413) so that we can avoid splitting manually. Also updating the URI automatically as we did previously might be weird for the user's expectations so I'm investigating that too.

In any case let me work on this in the customer issue and I'll keep you posted.

**Comment by atsakiridis** [comment]
@abdulazizali77 since both username and domain should be allowed to have the dash character I'm adding a simple fix for now to not replace the dash character. I have also opened issue #696 for the future to improve validations and not resort to messing with the URI as we do now which is poor user experience.

Let me know if you have any concerns, otherwise we can close this one

**Comment by abdulazizali77** [comment]
@atsakiridis Antonis that makes sense, i will close this
