### ISSUE TITLE
There is no import library ?

### ISSUE THREAD

**Issue by mertgunay** [RestComm/restcomm-android-sdk#706]
I want to ask you a basic question.

Are you thinking about add compile library like 
compile 'org.com.restcom.android.4-2 ' ?

**Comment by atsakiridis** [comment]
@mertgunay the restcomm android SDK is already distributed via Maven. So you can use a compile dependency like:

compile 'org.restcomm:restcomm-android-sdk:1.0.3-BETA6-134'

In your App's build.gradle file. Closing issue for now, please let me know if it's still unclear. Also please prefer to open such questions either in our [forum](https://groups.google.com/forum/#!forum/restcomm) or in Stackoverflow (tag 'restcomm'), so that the community can benefit more from it

Best regards,
Antonis

**Comment by mertgunay** [comment]
I'am getting this errror

Error:Failed to resolve: org.restcomm.android:libwebrtc:1.0.0-beta5-16765 during compile this library
" compile 'org.restcomm:restcomm-android-sdk:1.0.4-BETA7-163' "

**Comment by mertgunay** [comment]
Okey I solved my problem adding this code block to app > build.gradle

repositories {
    mavenCentral()
    maven {
        url "http://telestax.jfrog.io/telestax/community-releases"
    }
}
