### ISSUE TITLE
Change RCDevice service when in background and call is initiated via push

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-android-sdk#748]
- When client application is bound to service, do not start it. When its unbound stop the service-  -
- When local notification is shown to user, and user taps on hangup we should remove notification and stop service.
- When local notification is shown to user, and user taps on audio/video Olympus app should be opened (with bind option) and call should be placed
- Changes should be tested with all android os versions from 5.0

**Comment by atsakiridis** [comment]
@ognjenns here are some comments from my testing session of this PR:
- When receiving call in the background and answering by tapping outside of any of the small buttons of the notification I'm sent to the App where I accept the call as audio and then get 'ICE server JSON parsing error: ...Value error at s of type ....String cannot be converted to int'
- Need to think about FCM SERVER KEY, right now it's impossible to use Android Olympus without changing the source. Need to consider secure storage for this, so that a new user downloading the App can actually use it. And we need to do it in a way that for customers using the SDK they don't need to store it statically or it can be reverse engineered. Let's open new issue for this and place it in Upcoming sprint, 'Backlog' pipeline
- Olympus > Push Notifications Settings > 'Http Domain' seems weird; let's make it 'Restcomm Connect Domain' 
- Can we hide passwords and emails from logs: 12-13 12:10:40.353 27997-28887/org.restcomm.android.olympus I/JainSipClient: reconfigure(): {push-account-email=<remove from here>, push-account-password=<remove from here>}? In general let's review logs and see if any other push related credential is leaked
- Can we shorten log TAG for FCM entities' logs to make them more consistent with other and not take too much space: `12-13 12:10:40.355 27997-29719/org.restcomm.android.olympus V/org.restcomm.android.sdk.fcm.FcmConfigurationHandler: Getting an account sid`? Let's just make it `FcmConfigurationHandler`
- Can we update: `12-13 12:10:44.250 27997-27997/org.restcomm.android.olympus I/RCDevice: Device and user are successfully registered!` in to `12-13 12:10:44.250 27997-27997/org.restcomm.android.olympus I/RCDevice: Device and user are successfully registered for Push Notifications!` because right now it' now clear what the registration is about
- Unfortunately UX for toast with warning for push notifications settings missing/errors doesn't seem to help much; user doesn't really notice that push notifications were messed up. Another issue is that when the user actually fixes the settings and updates, there is not notification in the UI that registration with Push actually succeeded; we need to revisit. Can you think about alternative solutions as part of #767? We can discuss together before going ahead with implementation
