### ISSUE TITLE
Enable/disable push notifications on server

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-android-sdk#749]
- We need to be able to enable/disable push notifications on server from client

**Comment by atsakiridis** [comment]
Need to configure client entity on the server and set isPushEnabled = true

**Comment by ognjenns** [comment]
We should make the text changes on settings for enable/disable push.

**Comment by atsakiridis** [comment]
Also, some things I noticed when testing Push Notifications that we can verify after we fix this:
- When I try to disable Push Notifications from Settings after they have been successfully enabled I get: ‘Push notifications configuration failed, status: Failed to register/update for push notification; Client sid cannot be found’. Shouldn’t we disable them by removing related entities from Push/RC servers?
- On the same area as previous point, what happens if we want to change Push Notification server for example from staging to cloud in terms of push configuration in RC/Push servers? Will existing Olympus users be able to migrate to new release without fresh install? 

Let's discuss more with Oleg
