### ISSUE TITLE
Secure Websocket connection

### ISSUE THREAD

**Issue by WolandPL** [RestComm/restcomm-android-sdk#778]
How to configure a connection to Restcomm server via Secure Websocket (WSS)?

I'm currently using Restcomm server via websocket and everything is working fine. But when trying to use secure version, I cannot connect from Android to the server. What change should I do in the configuration?

I tried simply setting SIGNALING_SECURE_ENABLED to true and leave anything else unchanged - no connection.

When I try to add "wss:" prefix in front of SIGNALING_DOMAIN I got an exception (SDK doesn't expect any protocol in front of the address).

In your code I found WSS commented out in jainSipClientBind method of JainSipClient. Does it mean WSS is not supported?

**Comment by atsakiridis** [comment]
@WolandPL by using 'wss' instead of 'tls' in jainSipClientBind you can enable wss for secure signaling, but the problem is that we currently have a [regression](https://github.com/RestComm/restcomm-android-sdk/issues/744) that is related to introduction of DNS SRV. Seems that DNS SRV doesn't work well with wss. Once we fix #744 you should be able to use wss. I'd suggest monitoring #744.

Hope that helps

Best regards,
Antonis
