### ISSUE TITLE
Only first message is shown after tap on notification

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-android-sdk#826]
We receive more than one message via push notification, when we  tap on the notification message screen is opened and only first message is shown.

**Comment by atsakiridis** [comment]
@ognjenns the problem here is the original design decision where SDK is not responsible for storing messages; it falls under App’s jurisdiction, and with push notifications introduction, the only way App can be notified of all messages is to be woken each time a notification arrives, which is, of course impossible. Let me know if you see good way around this; if not we need to add it in the list of things that require heavy refactoring + brainstorming and tackle after release.

**Comment by atsakiridis** [comment]
Per discussion in daily, this needs heavy refactoring and must be deferred for later

**Comment by atsakiridis** [comment]
Dup of #392
